### ISSUE TITLE
status=dead

### ISSUE THREAD

**Issue by dik0st** [tontechio/pow-miner-gpu-hiveos#12]
Добрый день. настраиваю майнинг на hiveOS, сделал все по инструкции. после запуска майнера - такой вот статус. подскажите, куда копать?

**Comment by zheselevko** [comment]
первое то что статус а второй момент что через некоторое время майнер перестает работать а в статистике отображется что работает но через терминал отображает что не запущен

**Comment by dik0st** [comment]
нашел решение, в режиме консоли останавливаете майнер, прописываете две команды:
ДЛЯ CUDA
/hive/miners/custom/custom-get https://github.com/tontechio/pow-miner-gpu-hiveos/releases/download/h-20211122-1/tonminer_cuda_hiveos_x86_64.tar.gz -f 

/hive/miners/custom/custom-get https://github.com/tontechio/pow-miner-gpu-hiveos/releases/download/h-20211124-1/tonminer_cuda_hiveos_x86_64.tar.gz -f 

ДЛЯ OPENCL
/hive/miners/custom/custom-get https://github.com/tontechio/pow-miner-gpu-hiveos/releases/download/h-20211122-1/tonminer_opencl_hiveos_x86_64.tar.gz -f 

/hive/miners/custom/custom-get https://github.com/tontechio/pow-miner-gpu-hiveos/releases/download/h-20211124-1/tonminer_opencl_hiveos_x86_64.tar.gz -f

И стартуете майнер. статус становится running.

**Comment by MyProxy** [comment]
same problem on `h.20211126.1` version, got error , crash and stop working some of gpu miners.

**Comment by tontechio** [comment]
Fixed: https://github.com/tontechio/pow-miner-gpu-hiveos/releases/tag/h.20211126.1

**Comment by tontechio** [comment]
> same problem on `h.20211126.1` latest version, got error , crash and stop working some of gpu miners.

please show me version output
`/hive/miners/custom/tonminer_opencl_hiveos_x86_64/assets/tonlib-cuda-cli -V`
or (if you use opencl)
`/hive/miners/custom/tonminer_opencl_hiveos_x86_64/assets/tonlib-opencl-cli -V`

**Comment by MyProxy** [comment]
tonlib-cli build information: [ Commit: 13b71a4b81de56ab7d4a0d21a14e69c9e6186a0d, Date: 2021-11-26 21:20:50 +0300]

**Comment by MyProxy** [comment]
tonlib-cli build information: [ Commit: 13b71a4b81de56ab7d4a0d21a14e69c9e6186a0d, Date: 2021-11-26 21:20:50 +0300]

Made another issue with exactly error at : https://github.com/tontechio/pow-miner-gpu/issues/103

**Comment by tontechio** [comment]
Got it. This is related to miner itself, so I close issue here. Thanks for report
