### ISSUE TITLE
1080 only 400mh, but benchmark shows 1500mh

### ISSUE THREAD

**Issue by AeShevch** [tontechio/pow-miner-gpu-hiveos#15]
What overclocking settings are needed for TON? 
Why does p106-100(1060) have a 2 times higher hashrate than 1080?

tonminer_cuda_hiveos_x86_64-h.20211130.1

"miner_0": ["kf-P_TOdwcCh0AXHhBpICDMxStxHenWdLCDLNH5QcNpwMHJ8",0,32,0,2],
"miner_1": ["kf-P_TOdwcCh0AXHhBpICDMxStxHenWdLCDLNH5QcNpwMHJ8",1,32,0,2],
"tmpfs_logs_enable": "yes"

![Снимок экрана 2021-12-07 в 10 33 42](https://user-images.githubusercontent.com/44289476/144985998-506fab28-cae5-40e2-97dc-c9a21f7dec79.png)

**Comment by AeShevch** [comment]
Launched the benchmark:
![Снимок экрана 2021-12-09 в 1 13 01](https://user-images.githubusercontent.com/44289476/145293703-93facbde-e707-46b2-a2b2-7302d67f25dd.png)

It says that with a boost factor of 32, the hashrate should be about 1500mh, but it is only 400mh. What am I doing wrong?

**Comment by tontechio** [comment]
Benchmark show simplified result and key value is a boost factor, not a hash rate in a test.
