### ISSUE TITLE
status-tonminer-miner_0.json: No such file or directory

### ISSUE THREAD

**Issue by aavanesov** [tontechio/pow-miner-gpu-hiveos#5]
Hello.

I faced and error while setting up the miner according to the published guide for HiveOS.
6xAMD RX580 GPUs.

Flight list config is attached. 
[8415080_Toncoin.json.txt](https://github.com/tontechio/pow-miner-gpu-hiveos/files/7579939/8415080_Toncoin.json.txt)

Miner log:
...
onminer-miner_0.service
INFO: start tonminer-miner_1.service
INFO: start tonminer-miner_2.service
INFO: start tonminer-miner_3.service
INFO: start tonminer-miner_4.service
INFO: start tonminer-miner_5.service
INFO: ALL STARTED
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_0.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_1.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_2.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_3.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_4.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_5.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_0.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_1.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_2.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_3.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_4.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_5.json: No such file or directory
cat: /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_0.json: No such file or directory
...

**Comment by tontechio** [comment]
Fix: https://github.com/tontechio/pow-miner-gpu-hiveos/releases/tag/h-20211122-1

**Comment by aavanesov** [comment]
Thanks, I appreciate your work.
BTW, I believe that the issue in my case was related to the old Ubuntu version used by HiveOS (Ubuntu 16).
