### ISSUE TITLE
Problem with mixed NV/AMD cards in a rig

### ISSUE THREAD

**Issue by MRusinov** [tontechio/pow-miner-gpu-hiveos#8]
I have a rig with mixed cards, two NVidia and four AMD. Can't find a way to correctly install simultaneously two custom miners for Ton (Cuda and OpenCL).

**Comment by SevadaSahakyan** [comment]
Same here. "Miners can't be duplicated in same flight sheet".

**Comment by tontechio** [comment]
Currently we do not support mixed Nvidia/AMD rigs
