### ISSUE TITLE
Problem with cards , more than 10 cards do not work in riga

### ISSUE THREAD

**Issue by zheselevko** [tontechio/pow-miner-gpu-hiveos#9]
[miner_10] status=dead, ERROR: file not exists /hive/miners/custom/tonminer_cuda_hiveos_x86_64/logs/status-tonminer-miner_10.json                                                                                  
[miner_11] status=dead, ERROR: file not exists /hive/miners/custom/tonminer_cuda_hiveos_x86_64/logs/status-tonminer-miner_11.json

**Comment by tontechio** [comment]
fix: https://github.com/tontechio/pow-miner-gpu-hiveos/releases/tag/h-20211124-1

**Comment by theromba** [comment]
[miner_0] status=running, ERROR: file not exists /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_0.json                                                                           
[miner_1] status=auto-restart, ERROR: file not exists /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_1.json                                                                      
[miner_2] status=auto-restart, ERROR: file not exists /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_2.json                                                                      
[miner_3] status=running, ERROR: file not exists /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_3.json                                                                           
[miner_4] status=auto-restart, ERROR: file not exists /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_4.json                                                                      
[miner_5] status=auto-restart, ERROR: file not exists /hive/miners/custom/tonminer_opencl_hiveos_x86_64/logs/status-tonminer-miner_5.json

OPENCL don`t fix.




> fix: https://github.com/tontechio/pow-miner-gpu-hiveos/releases/tag/h-20211124-1
